[Alice]
id = 41131JEHN09843
passord = caline
passordstyrke = 0.50
type = fysisk

[Bob]
id = 3A161JEHN09286
passord = diva13
passordstyrke = 0.50
type = fysisk

[Charlie]
id = 34061FDH2003BL
passord = easyas123
passordstyrke = 0.58
type = fysisk

[Dave]
id = emulator-5554
passord = shifty
passordstyrke = 0.50
type = lokal

[Frode]
id = emulator-5556
passord = teamojunior
passordstyrke = 0.83
type = ekstern-1

[Grace]
id = emulator-5558
passord = samantha2
passordstyrke = 0.58
type = ekstern-1

[Heidi]
id = emulator-5560
passord = 260193
passordstyrke = 0.50
type = ekstern-2

[Ivan]
id = emulator-5562
passord = maria13
passordstyrke = 0.50
type = ekstern-2
